/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ItemType = IDL.Variant({ 'rank' : IDL.Null, 'crate' : IDL.Null });
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'username' : IDL.Text,
  'timestamp' : IDL.Int,
  'itemName' : IDL.Text,
  'itemType' : ItemType,
  'quantity' : IDL.Nat,
  'price' : IDL.Float64,
});
export const Crate = IDL.Record({
  'name' : IDL.Text,
  'unit' : IDL.Text,
  'price' : IDL.Float64,
});
export const Rank = IDL.Record({ 'name' : IDL.Text, 'price' : IDL.Float64 });

export const idlService = IDL.Service({
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCrates' : IDL.Func([], [IDL.Vec(Crate)], ['query']),
  'getOrderCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getOrdersByUsername' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getRanks' : IDL.Func([], [IDL.Vec(Rank)], ['query']),
  'submitOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ItemType = IDL.Variant({ 'rank' : IDL.Null, 'crate' : IDL.Null });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'username' : IDL.Text,
    'timestamp' : IDL.Int,
    'itemName' : IDL.Text,
    'itemType' : ItemType,
    'quantity' : IDL.Nat,
    'price' : IDL.Float64,
  });
  const Crate = IDL.Record({
    'name' : IDL.Text,
    'unit' : IDL.Text,
    'price' : IDL.Float64,
  });
  const Rank = IDL.Record({ 'name' : IDL.Text, 'price' : IDL.Float64 });
  
  return IDL.Service({
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCrates' : IDL.Func([], [IDL.Vec(Crate)], ['query']),
    'getOrderCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getOrdersByUsername' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getRanks' : IDL.Func([], [IDL.Vec(Rank)], ['query']),
    'submitOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };