/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Crate { 'name' : string, 'unit' : string, 'price' : number }
export type ItemType = { 'rank' : null } |
  { 'crate' : null };
export interface Order {
  'id' : bigint,
  'username' : string,
  'timestamp' : bigint,
  'itemName' : string,
  'itemType' : ItemType,
  'quantity' : bigint,
  'price' : number,
}
export interface Rank { 'name' : string, 'price' : number }
export interface _SERVICE {
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCrates' : ActorMethod<[], Array<Crate>>,
  'getOrderCount' : ActorMethod<[], bigint>,
  'getOrdersByUsername' : ActorMethod<[string], Array<Order>>,
  'getRanks' : ActorMethod<[], Array<Rank>>,
  'submitOrder' : ActorMethod<[string, string, string, number, bigint], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];